
all:
  children:
    atlas:
      hosts:
        atlas_server:
          ansible_host: i-02a3e51ebfd2efcfa
          ansible_connection: amazon.aws.aws_ssm
          ansible_aws_ssm_region: ap-south-1
          ansible_aws_ssm_bucket_name: atlas-dev-ansible-ssm-d1510d1667b1f1da76722e30eb
          ansible_user: ec2-user
